package test.java.com.uttesh.selenium.Tests;


import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import java.util.concurrent.TimeUnit;


import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.Listeners;
import org.testng.annotations.Parameters;
/**
 * Test class as generated by the Selenium IDE
 *
 */
@Listeners(ScreenshotListener.class)
public class AmazonNigelSlaterTest extends BaseTest{
  private WebDriver driver;
  private String baseUrl;
  private boolean acceptNextAlert = true;
  private StringBuffer verificationErrors = new StringBuffer();

  @Parameters({ "platform","browser","version", "url" })
  @BeforeClass
  public void setUp(String platform, String browser, String version, String url) throws Exception {
    driver = getRemoteWebDriver(platform,browser,version,url);
    baseUrl = "http://www.amazon.com/";
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
  }

  @Test
  public void NigelTest() throws Exception {
    driver.get(baseUrl + "/");
    driver.findElement(By.id("twotabsearchtextbox")).click();
    driver.findElement(By.id("twotabsearchtextbox")).clear();
    driver.findElement(By.id("twotabsearchtextbox")).sendKeys("nigel slater");
    driver.findElement(By.cssSelector("input.nav-submit-input")).click();
    driver.findElement(By.cssSelector("span.lrg.bold")).click();
    // Warning: verifyTextPresent may require manual changes
    try {
      //assertTr(driver.findElement(By.cssSelector("BODY")).getText().matches("^[\\s\\S]*ISBN-10: 1607740370[\\s\\S]*$"));
    } catch (Error e) {
      verificationErrors.append(e.toString());
    }
  }

}
