package test.java.com.uttesh.selenium.Tests;

import static org.junit.Assert.assertTrue;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.Listeners;
import org.testng.annotations.Parameters;
import test.java.com.uttesh.selenium.Tests.pages.AmazonHome;

/**
 * Page Object pattern implementation of the default class generated by the
 * Selenium IDE
 * 
 * The test performed here is to go to amazon.com, search for "nigel slater",
 * click on the first link in the search results and verify that an ISBN is
 * found on the page with the book details
 */
@Listeners(ScreenshotListener.class)
public class AmazonTest extends BaseTest {

	private WebDriver driver;

        @Parameters({ "platform","browser","version", "url" })
	@BeforeClass
	public void setUp(String platform, String browser, String version, String url) {
            driver = getRemoteWebDriver(platform,browser,version,url);
	}

	@Test
	public void bookSearchTest() {
		assertTrue(new AmazonHome(driver).searchFor("nigel slater").clickOnBookLink().isISBNFoundOnPage("1607740370"));
	}
       
        

}
